/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as SearchRouteImport } from './routes/search'
import { Route as SitemapAnimationsDotxmlRouteImport } from './routes/sitemap-animations[.]xml'
import { Route as SitemapImagesDotxmlRouteImport } from './routes/sitemap-images[.]xml'
import { Route as SitemapLugandaMoviesDotxmlRouteImport } from './routes/sitemap-luganda-movies[.]xml'
import { Route as SitemapLuoMoviesDotxmlRouteImport } from './routes/sitemap-luo-movies[.]xml'
import { Route as SitemapMoviesDotxmlRouteImport } from './routes/sitemap-movies[.]xml'
import { Route as SitemapPagesDotxmlRouteImport } from './routes/sitemap-pages[.]xml'
import { Route as SitemapSeriesDotxmlRouteImport } from './routes/sitemap-series[.]xml'
import { Route as SitemapVideosDotxmlRouteImport } from './routes/sitemap-videos[.]xml'
import { Route as SitemapVjDotxmlRouteImport } from './routes/sitemap-vj[.]xml'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as TutorialRouteImport } from './routes/tutorial'
import { Route as CategorySlugRouteImport } from './routes/category.$slug'
import { Route as LugandaIndexRouteImport } from './routes/luganda.index'
import { Route as LugandaIdRouteImport } from './routes/luganda.$id'
import { Route as LuoIndexRouteImport } from './routes/luo.index'
import { Route as LuoIdRouteImport } from './routes/luo.$id'
import { Route as PayIdRouteImport } from './routes/pay.$id'
import { Route as TesoIndexRouteImport } from './routes/teso.index'
import { Route as TesoIdRouteImport } from './routes/teso.$id'
import { Route as WatchIdRouteImport } from './routes/watch.$id'
import { Route as ApiPublicMovieRouteImport } from './routes/api/public/movie'
import { Route as ApiPublicStreamRouteImport } from './routes/api/public/stream'
import { Route as ApiPublicSubtitleRouteImport } from './routes/api/public/subtitle'
import { Route as PProviderIndexRouteImport } from './routes/p.$provider.index'
import { Route as PProviderIdRouteImport } from './routes/p.$provider.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const SearchRoute = SearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapAnimationsDotxmlRoute = SitemapAnimationsDotxmlRouteImport.update({
  id: '/sitemap-animations.xml',
  path: '/sitemap-animations.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapImagesDotxmlRoute = SitemapImagesDotxmlRouteImport.update({
  id: '/sitemap-images.xml',
  path: '/sitemap-images.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapLugandaMoviesDotxmlRoute =
  SitemapLugandaMoviesDotxmlRouteImport.update({
    id: '/sitemap-luganda-movies.xml',
    path: '/sitemap-luganda-movies.xml',
    getParentRoute: () => rootRouteImport,
  } as any)
const SitemapLuoMoviesDotxmlRoute = SitemapLuoMoviesDotxmlRouteImport.update({
  id: '/sitemap-luo-movies.xml',
  path: '/sitemap-luo-movies.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapMoviesDotxmlRoute = SitemapMoviesDotxmlRouteImport.update({
  id: '/sitemap-movies.xml',
  path: '/sitemap-movies.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapPagesDotxmlRoute = SitemapPagesDotxmlRouteImport.update({
  id: '/sitemap-pages.xml',
  path: '/sitemap-pages.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapSeriesDotxmlRoute = SitemapSeriesDotxmlRouteImport.update({
  id: '/sitemap-series.xml',
  path: '/sitemap-series.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapVideosDotxmlRoute = SitemapVideosDotxmlRouteImport.update({
  id: '/sitemap-videos.xml',
  path: '/sitemap-videos.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapVjDotxmlRoute = SitemapVjDotxmlRouteImport.update({
  id: '/sitemap-vj.xml',
  path: '/sitemap-vj.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const TutorialRoute = TutorialRouteImport.update({
  id: '/tutorial',
  path: '/tutorial',
  getParentRoute: () => rootRouteImport,
} as any)
const CategorySlugRoute = CategorySlugRouteImport.update({
  id: '/category/$slug',
  path: '/category/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LugandaIndexRoute = LugandaIndexRouteImport.update({
  id: '/luganda/',
  path: '/luganda/',
  getParentRoute: () => rootRouteImport,
} as any)
const LugandaIdRoute = LugandaIdRouteImport.update({
  id: '/luganda/$id',
  path: '/luganda/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const LuoIndexRoute = LuoIndexRouteImport.update({
  id: '/luo/',
  path: '/luo/',
  getParentRoute: () => rootRouteImport,
} as any)
const LuoIdRoute = LuoIdRouteImport.update({
  id: '/luo/$id',
  path: '/luo/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const PayIdRoute = PayIdRouteImport.update({
  id: '/pay/$id',
  path: '/pay/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const TesoIndexRoute = TesoIndexRouteImport.update({
  id: '/teso/',
  path: '/teso/',
  getParentRoute: () => rootRouteImport,
} as any)
const TesoIdRoute = TesoIdRouteImport.update({
  id: '/teso/$id',
  path: '/teso/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchIdRoute = WatchIdRouteImport.update({
  id: '/watch/$id',
  path: '/watch/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicMovieRoute = ApiPublicMovieRouteImport.update({
  id: '/api/public/movie',
  path: '/api/public/movie',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicStreamRoute = ApiPublicStreamRouteImport.update({
  id: '/api/public/stream',
  path: '/api/public/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicSubtitleRoute = ApiPublicSubtitleRouteImport.update({
  id: '/api/public/subtitle',
  path: '/api/public/subtitle',
  getParentRoute: () => rootRouteImport,
} as any)
const PProviderIndexRoute = PProviderIndexRouteImport.update({
  id: '/p/$provider/',
  path: '/p/$provider/',
  getParentRoute: () => rootRouteImport,
} as any)
const PProviderIdRoute = PProviderIdRouteImport.update({
  id: '/p/$provider/$id',
  path: '/p/$provider/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/search': typeof SearchRoute
  '/sitemap-animations.xml': typeof SitemapAnimationsDotxmlRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-luganda-movies.xml': typeof SitemapLugandaMoviesDotxmlRoute
  '/sitemap-luo-movies.xml': typeof SitemapLuoMoviesDotxmlRoute
  '/sitemap-movies.xml': typeof SitemapMoviesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-series.xml': typeof SitemapSeriesDotxmlRoute
  '/sitemap-videos.xml': typeof SitemapVideosDotxmlRoute
  '/sitemap-vj.xml': typeof SitemapVjDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutorial': typeof TutorialRoute
  '/category/$slug': typeof CategorySlugRoute
  '/luganda/$id': typeof LugandaIdRoute
  '/luo/$id': typeof LuoIdRoute
  '/pay/$id': typeof PayIdRoute
  '/teso/$id': typeof TesoIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/luganda/': typeof LugandaIndexRoute
  '/luo/': typeof LuoIndexRoute
  '/teso/': typeof TesoIndexRoute
  '/api/public/movie': typeof ApiPublicMovieRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/api/public/subtitle': typeof ApiPublicSubtitleRoute
  '/p/$provider/$id': typeof PProviderIdRoute
  '/p/$provider/': typeof PProviderIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/search': typeof SearchRoute
  '/sitemap-animations.xml': typeof SitemapAnimationsDotxmlRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-luganda-movies.xml': typeof SitemapLugandaMoviesDotxmlRoute
  '/sitemap-luo-movies.xml': typeof SitemapLuoMoviesDotxmlRoute
  '/sitemap-movies.xml': typeof SitemapMoviesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-series.xml': typeof SitemapSeriesDotxmlRoute
  '/sitemap-videos.xml': typeof SitemapVideosDotxmlRoute
  '/sitemap-vj.xml': typeof SitemapVjDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutorial': typeof TutorialRoute
  '/category/$slug': typeof CategorySlugRoute
  '/luganda/$id': typeof LugandaIdRoute
  '/luo/$id': typeof LuoIdRoute
  '/pay/$id': typeof PayIdRoute
  '/teso/$id': typeof TesoIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/luganda': typeof LugandaIndexRoute
  '/luo': typeof LuoIndexRoute
  '/teso': typeof TesoIndexRoute
  '/api/public/movie': typeof ApiPublicMovieRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/api/public/subtitle': typeof ApiPublicSubtitleRoute
  '/p/$provider/$id': typeof PProviderIdRoute
  '/p/$provider': typeof PProviderIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/search': typeof SearchRoute
  '/sitemap-animations.xml': typeof SitemapAnimationsDotxmlRoute
  '/sitemap-images.xml': typeof SitemapImagesDotxmlRoute
  '/sitemap-luganda-movies.xml': typeof SitemapLugandaMoviesDotxmlRoute
  '/sitemap-luo-movies.xml': typeof SitemapLuoMoviesDotxmlRoute
  '/sitemap-movies.xml': typeof SitemapMoviesDotxmlRoute
  '/sitemap-pages.xml': typeof SitemapPagesDotxmlRoute
  '/sitemap-series.xml': typeof SitemapSeriesDotxmlRoute
  '/sitemap-videos.xml': typeof SitemapVideosDotxmlRoute
  '/sitemap-vj.xml': typeof SitemapVjDotxmlRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/tutorial': typeof TutorialRoute
  '/category/$slug': typeof CategorySlugRoute
  '/luganda/$id': typeof LugandaIdRoute
  '/luo/$id': typeof LuoIdRoute
  '/pay/$id': typeof PayIdRoute
  '/teso/$id': typeof TesoIdRoute
  '/watch/$id': typeof WatchIdRoute
  '/luganda/': typeof LugandaIndexRoute
  '/luo/': typeof LuoIndexRoute
  '/teso/': typeof TesoIndexRoute
  '/api/public/movie': typeof ApiPublicMovieRoute
  '/api/public/stream': typeof ApiPublicStreamRoute
  '/api/public/subtitle': typeof ApiPublicSubtitleRoute
  '/p/$provider/$id': typeof PProviderIdRoute
  '/p/$provider/': typeof PProviderIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/search'
    | '/sitemap-animations.xml'
    | '/sitemap-images.xml'
    | '/sitemap-luganda-movies.xml'
    | '/sitemap-luo-movies.xml'
    | '/sitemap-movies.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-series.xml'
    | '/sitemap-videos.xml'
    | '/sitemap-vj.xml'
    | '/sitemap.xml'
    | '/tutorial'
    | '/category/$slug'
    | '/luganda/$id'
    | '/luo/$id'
    | '/pay/$id'
    | '/teso/$id'
    | '/watch/$id'
    | '/luganda/'
    | '/luo/'
    | '/teso/'
    | '/api/public/movie'
    | '/api/public/stream'
    | '/api/public/subtitle'
    | '/p/$provider/$id'
    | '/p/$provider/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/search'
    | '/sitemap-animations.xml'
    | '/sitemap-images.xml'
    | '/sitemap-luganda-movies.xml'
    | '/sitemap-luo-movies.xml'
    | '/sitemap-movies.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-series.xml'
    | '/sitemap-videos.xml'
    | '/sitemap-vj.xml'
    | '/sitemap.xml'
    | '/tutorial'
    | '/category/$slug'
    | '/luganda/$id'
    | '/luo/$id'
    | '/pay/$id'
    | '/teso/$id'
    | '/watch/$id'
    | '/luganda'
    | '/luo'
    | '/teso'
    | '/api/public/movie'
    | '/api/public/stream'
    | '/api/public/subtitle'
    | '/p/$provider/$id'
    | '/p/$provider'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/search'
    | '/sitemap-animations.xml'
    | '/sitemap-images.xml'
    | '/sitemap-luganda-movies.xml'
    | '/sitemap-luo-movies.xml'
    | '/sitemap-movies.xml'
    | '/sitemap-pages.xml'
    | '/sitemap-series.xml'
    | '/sitemap-videos.xml'
    | '/sitemap-vj.xml'
    | '/sitemap.xml'
    | '/tutorial'
    | '/category/$slug'
    | '/luganda/$id'
    | '/luo/$id'
    | '/pay/$id'
    | '/teso/$id'
    | '/watch/$id'
    | '/luganda/'
    | '/luo/'
    | '/teso/'
    | '/api/public/movie'
    | '/api/public/stream'
    | '/api/public/subtitle'
    | '/p/$provider/$id'
    | '/p/$provider/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  SearchRoute: typeof SearchRoute
  SitemapAnimationsDotxmlRoute: typeof SitemapAnimationsDotxmlRoute
  SitemapImagesDotxmlRoute: typeof SitemapImagesDotxmlRoute
  SitemapLugandaMoviesDotxmlRoute: typeof SitemapLugandaMoviesDotxmlRoute
  SitemapLuoMoviesDotxmlRoute: typeof SitemapLuoMoviesDotxmlRoute
  SitemapMoviesDotxmlRoute: typeof SitemapMoviesDotxmlRoute
  SitemapPagesDotxmlRoute: typeof SitemapPagesDotxmlRoute
  SitemapSeriesDotxmlRoute: typeof SitemapSeriesDotxmlRoute
  SitemapVideosDotxmlRoute: typeof SitemapVideosDotxmlRoute
  SitemapVjDotxmlRoute: typeof SitemapVjDotxmlRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TutorialRoute: typeof TutorialRoute
  CategorySlugRoute: typeof CategorySlugRoute
  LugandaIdRoute: typeof LugandaIdRoute
  LuoIdRoute: typeof LuoIdRoute
  PayIdRoute: typeof PayIdRoute
  TesoIdRoute: typeof TesoIdRoute
  WatchIdRoute: typeof WatchIdRoute
  LugandaIndexRoute: typeof LugandaIndexRoute
  LuoIndexRoute: typeof LuoIndexRoute
  TesoIndexRoute: typeof TesoIndexRoute
  ApiPublicMovieRoute: typeof ApiPublicMovieRoute
  ApiPublicStreamRoute: typeof ApiPublicStreamRoute
  ApiPublicSubtitleRoute: typeof ApiPublicSubtitleRoute
  PProviderIdRoute: typeof PProviderIdRoute
  PProviderIndexRoute: typeof PProviderIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/search': {
      id: '/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof SearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-animations.xml': {
      id: '/sitemap-animations.xml'
      path: '/sitemap-animations.xml'
      fullPath: '/sitemap-animations.xml'
      preLoaderRoute: typeof SitemapAnimationsDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-images.xml': {
      id: '/sitemap-images.xml'
      path: '/sitemap-images.xml'
      fullPath: '/sitemap-images.xml'
      preLoaderRoute: typeof SitemapImagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-luganda-movies.xml': {
      id: '/sitemap-luganda-movies.xml'
      path: '/sitemap-luganda-movies.xml'
      fullPath: '/sitemap-luganda-movies.xml'
      preLoaderRoute: typeof SitemapLugandaMoviesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-luo-movies.xml': {
      id: '/sitemap-luo-movies.xml'
      path: '/sitemap-luo-movies.xml'
      fullPath: '/sitemap-luo-movies.xml'
      preLoaderRoute: typeof SitemapLuoMoviesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-movies.xml': {
      id: '/sitemap-movies.xml'
      path: '/sitemap-movies.xml'
      fullPath: '/sitemap-movies.xml'
      preLoaderRoute: typeof SitemapMoviesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-pages.xml': {
      id: '/sitemap-pages.xml'
      path: '/sitemap-pages.xml'
      fullPath: '/sitemap-pages.xml'
      preLoaderRoute: typeof SitemapPagesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-series.xml': {
      id: '/sitemap-series.xml'
      path: '/sitemap-series.xml'
      fullPath: '/sitemap-series.xml'
      preLoaderRoute: typeof SitemapSeriesDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-videos.xml': {
      id: '/sitemap-videos.xml'
      path: '/sitemap-videos.xml'
      fullPath: '/sitemap-videos.xml'
      preLoaderRoute: typeof SitemapVideosDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap-vj.xml': {
      id: '/sitemap-vj.xml'
      path: '/sitemap-vj.xml'
      fullPath: '/sitemap-vj.xml'
      preLoaderRoute: typeof SitemapVjDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tutorial': {
      id: '/tutorial'
      path: '/tutorial'
      fullPath: '/tutorial'
      preLoaderRoute: typeof TutorialRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/category/$slug': {
      id: '/category/$slug'
      path: '/category/$slug'
      fullPath: '/category/$slug'
      preLoaderRoute: typeof CategorySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luganda/': {
      id: '/luganda/'
      path: '/luganda'
      fullPath: '/luganda/'
      preLoaderRoute: typeof LugandaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luganda/$id': {
      id: '/luganda/$id'
      path: '/luganda/$id'
      fullPath: '/luganda/$id'
      preLoaderRoute: typeof LugandaIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luo/': {
      id: '/luo/'
      path: '/luo'
      fullPath: '/luo/'
      preLoaderRoute: typeof LuoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luo/$id': {
      id: '/luo/$id'
      path: '/luo/$id'
      fullPath: '/luo/$id'
      preLoaderRoute: typeof LuoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$id': {
      id: '/pay/$id'
      path: '/pay/$id'
      fullPath: '/pay/$id'
      preLoaderRoute: typeof PayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teso/': {
      id: '/teso/'
      path: '/teso'
      fullPath: '/teso/'
      preLoaderRoute: typeof TesoIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teso/$id': {
      id: '/teso/$id'
      path: '/teso/$id'
      fullPath: '/teso/$id'
      preLoaderRoute: typeof TesoIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watch/$id': {
      id: '/watch/$id'
      path: '/watch/$id'
      fullPath: '/watch/$id'
      preLoaderRoute: typeof WatchIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/movie': {
      id: '/api/public/movie'
      path: '/api/public/movie'
      fullPath: '/api/public/movie'
      preLoaderRoute: typeof ApiPublicMovieRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/stream': {
      id: '/api/public/stream'
      path: '/api/public/stream'
      fullPath: '/api/public/stream'
      preLoaderRoute: typeof ApiPublicStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/subtitle': {
      id: '/api/public/subtitle'
      path: '/api/public/subtitle'
      fullPath: '/api/public/subtitle'
      preLoaderRoute: typeof ApiPublicSubtitleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$provider/': {
      id: '/p/$provider/'
      path: '/p/$provider'
      fullPath: '/p/$provider/'
      preLoaderRoute: typeof PProviderIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$provider/$id': {
      id: '/p/$provider/$id'
      path: '/p/$provider/$id'
      fullPath: '/p/$provider/$id'
      preLoaderRoute: typeof PProviderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  SearchRoute: SearchRoute,
  SitemapAnimationsDotxmlRoute: SitemapAnimationsDotxmlRoute,
  SitemapImagesDotxmlRoute: SitemapImagesDotxmlRoute,
  SitemapLugandaMoviesDotxmlRoute: SitemapLugandaMoviesDotxmlRoute,
  SitemapLuoMoviesDotxmlRoute: SitemapLuoMoviesDotxmlRoute,
  SitemapMoviesDotxmlRoute: SitemapMoviesDotxmlRoute,
  SitemapPagesDotxmlRoute: SitemapPagesDotxmlRoute,
  SitemapSeriesDotxmlRoute: SitemapSeriesDotxmlRoute,
  SitemapVideosDotxmlRoute: SitemapVideosDotxmlRoute,
  SitemapVjDotxmlRoute: SitemapVjDotxmlRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TutorialRoute: TutorialRoute,
  CategorySlugRoute: CategorySlugRoute,
  LugandaIdRoute: LugandaIdRoute,
  LuoIdRoute: LuoIdRoute,
  PayIdRoute: PayIdRoute,
  TesoIdRoute: TesoIdRoute,
  WatchIdRoute: WatchIdRoute,
  LugandaIndexRoute: LugandaIndexRoute,
  LuoIndexRoute: LuoIndexRoute,
  TesoIndexRoute: TesoIndexRoute,
  ApiPublicMovieRoute: ApiPublicMovieRoute,
  ApiPublicStreamRoute: ApiPublicStreamRoute,
  ApiPublicSubtitleRoute: ApiPublicSubtitleRoute,
  PProviderIdRoute: PProviderIdRoute,
  PProviderIndexRoute: PProviderIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
